/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Image;
//import java.awt.ToolKit;
/**
 *
 * @author kars
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /*
    public Image getIconImage() {
        Image retValue = ToolKit.getDefaultToolKit().getImage(ClassLoader.getSystemResource("imagenes/bancologo.png"));
        return retValue;
    }
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelAM = new javax.swing.JLabel();
        jLabelNommbres = new javax.swing.JLabel();
        jTextFieldAP = new javax.swing.JTextField();
        jButtonRegistrarse = new javax.swing.JButton();
        jLabelAP = new javax.swing.JLabel();
        jTextFieldAM = new javax.swing.JTextField();
        jTextFieldNombres = new javax.swing.JTextField();
        jLabelREgistro = new javax.swing.JLabel();
        jLabelNacimiento = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 80, -1));

        jLabelAM.setBackground(java.awt.Color.white);
        jLabelAM.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelAM.setForeground(java.awt.Color.white);
        jLabelAM.setText("Apellido materno:");
        getContentPane().add(jLabelAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabelNommbres.setBackground(java.awt.Color.white);
        jLabelNommbres.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelNommbres.setForeground(java.awt.Color.white);
        jLabelNommbres.setText("Nombres:");
        getContentPane().add(jLabelNommbres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        getContentPane().add(jTextFieldAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 210, -1));

        jButtonRegistrarse.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButtonRegistrarse.setText("Registrarse");
        jButtonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarseMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabelAP.setBackground(java.awt.Color.white);
        jLabelAP.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelAP.setForeground(java.awt.Color.white);
        jLabelAP.setText("Apellido paterno:");
        getContentPane().add(jLabelAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        getContentPane().add(jTextFieldAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 210, -1));
        getContentPane().add(jTextFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 210, -1));

        jLabelREgistro.setBackground(java.awt.Color.white);
        jLabelREgistro.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelREgistro.setForeground(java.awt.Color.white);
        jLabelREgistro.setText("Registro");
        getContentPane().add(jLabelREgistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabelNacimiento.setBackground(java.awt.Color.white);
        jLabelNacimiento.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelNacimiento.setForeground(java.awt.Color.white);
        jLabelNacimiento.setText("Fecha de nacimiento:");
        getContentPane().add(jLabelNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoPrincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 541, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarseMouseClicked
        System.out.println("registró");
    }//GEN-LAST:event_jButtonRegistrarseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JLabel jLabelAM;
    private javax.swing.JLabel jLabelAP;
    private javax.swing.JLabel jLabelNacimiento;
    private javax.swing.JLabel jLabelNommbres;
    private javax.swing.JLabel jLabelREgistro;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JTextField jTextFieldAM;
    private javax.swing.JTextField jTextFieldAP;
    private javax.swing.JTextField jTextFieldNombres;
    // End of variables declaration//GEN-END:variables
}
